Load organisations and many other imports
IFB-ElixirFr/ifbcat pull request #143
Opened 2021-03-08 21:55 UTC by guillaumecharbonnier

This PR should add several improvements for imports

2021-03-10 11:10 UTC, bryan-brancotte requested changes
Hello @guillaumecharbonnier

Beau boulot ! Je n'ai que quelques remarques. Pour info j'ai corrigé master pour que la CI passe, c'était un problème sur le viewset d'operatingSystem qui n'avait pas été vue à cause de ma typo. Bref fixed donc n'hésite pas à merge master dans ta branch pour voir si la CI passe. Ci après une remarque et une question:

### load_organisations_from_gridid.py
Le fichier `grid20201006.zip` est gros (je trouve) je ne sais pas comment il a été généré. On pourrait peut-être garder juste les 26 entrées pertinentes dans un `organisations_gridid.json` dans import_data, et qu'on note pour plus tard comment tu as généré le gros fichier, et comment faire le sous ensemble ? Ca accélérerait la CI car là on télécharge à chaque commit 40Mo depuis aws.

### tool/tool.py :
je ne comprend pas le champs downloads qui est un string, c'est le nombre de dowload de l'outils ? on met un download_count en integer nullable au cas où?

### team.py
En faites c'est une remarque à moi même, mais je vais faire sauter `user_profile`, en effet les `leaders` et `maintainers` peuvent editer et cela suffit, je pense que je vais appliquer cela au maximum dans les models une fois le merge fait.

2021-03-12 17:58 UTC, guillaumecharbonnier commented
Concernant le zip, je n'avais pas en perspective les CI au moment de l'écrire. J'ai remplacé cela par des requêtes à l'`API. Si tu veux en plus mettre en cache tu peux le faire tu as l'habitude.
https://github.com/IFB-ElixirFr/ifbcat/pull/143/commits/507d429e206ad5963eea7dcf6fb72848b7ed0ab1

Pour le champ download, j'ai dû l'activer à l'époque parce que je tenais à importer les quelques valeurs disponibles dans Drupal, mais à la réflexion cela ne sert pas vraiment de rajouter ce genre de métadonnées obsolètes. Je pencherai pour le re-supprimer.

Aussi en terme de modification de modèles, j'aimerai quadrupler la limite de caractères de l'accessibilityNote dans `event.py`, car j'ai certains trainings qui sont bavares en requirements...

Si tu es ok peux-tu faire ces modifs de modèles et merge cette branche ?

2021-03-15 09:44 UTC, bryan-brancotte commented
Hello @guillaumecharbonnier

Mise en cache ok

Pas de problème pour changer comme tu l'indique, au contraire ! Tu veux faire les changement avant ou après le merge ? Tu les fait ou tu veux que je m'en charge ?

P.S: accessibilityNote autant mettre un TextField

2021-03-15 09:48 UTC, bryan-brancotte approved these changes

2021-03-15 16:07 UTC, bryan-brancotte commented
so @guillaumecharbonnier merge ?

2021-03-15 16:15 UTC, guillaumecharbonnier commented
Suite à la réunion, il me semble qu'il faudrait aussi rajouter un M2M dans Service vers Tool car je ne vois nulle part pour faire référence à un outil.

2021-03-15 16:16 UTC, bryan-brancotte commented
Il y a deja Tool<->Team<->Service, est-ce suffisant dans un premier temps ?

2021-03-15 16:33 UTC, guillaumecharbonnier commented
Oui pour le merge.
Pas sûr pour le Tool<->Team<->Service suffisant car il me semble que tous les outils d'une équipe ne se retrouvent pas forcément dans un Service à partir du moment où un des outils l'est.
C'est fort probable que tu aies raison et que je dise n'importe quoi parce que je ne vois pas comment charger les infos dans ce cas de figure.

2021-03-15 16:39 UTC, bryan-brancotte commented
De toute façon là dans cette MR il n'y a pas le load des services ? Donc "pas grave" qu'on ai pas encore le liens tool<->service ?

2021-03-15 16:41 UTC, guillaumecharbonnier commented
Non pas grave du tout et pas de lien avec la branche, je rajoutais à la liste des choses à modifier dans les modèles.

2021-03-17 13:52 UTC, merged