WIP: Moving date information into two new fields in Event model
IFB-ElixirFr/ifbcat pull request #172
Opened 2021-11-25 09:57 UTC by Aziguy

Closing #159

2021-11-30 11:06 UTC, bryan-brancotte requested changes
Bonjour Hippolyte, ci joint mes remarques écrite sur la PR en cours.

2021-11-30 11:06 UTC, bryan-brancotte commented on ifbcat_api/model/event.py
> +    end_date = models.DateField(
Il faudra ajouter un validateur afin que l'on ne puisse pas mettre de end_date si start_date n'est pas définie.

2021-11-30 11:06 UTC, bryan-brancotte commented on ifbcat_api/model/training.py
> +            d, created = Event.objects.get_or_create(start_date=start_date, end_date=end_date)
Plutôt utiliser l'approche en ligne 133 : en ajouter les dates dans event_attrs

2021-11-30 11:06 UTC, bryan-brancotte commented on ifbcat_api/serializers.py
> +            'start_date',
:+1:

2021-11-30 11:06 UTC, bryan-brancotte commented on ifbcat_api/templatetags/ifbcat.py
> +                    Q(start_date=timezone.now()) | Q(end_date__isnull=False) & Q(end_date=timezone.now())
Il manque les `__gte` ce queryset contient les instances dans le futur, ou au moins pas encore achevées

2021-11-30 11:06 UTC, bryan-brancotte commented on ifbcat_api/views.py
> +            dateStartMin=Min('start_date'),
`dateStartMin` est équivalent à `start_date`, il faut donc retirer `dateStartMin`, et `Min(`

2021-11-30 11:06 UTC, bryan-brancotte commented on ifbcat_api/admin.py
>          start, end = (
Comme discuté, l'information de min et max sont maintenant présente dans start_date et end_date, on s'en sert directement et on retire donc ce bloque

2021-11-30 11:06 UTC, bryan-brancotte commented on ifbcat_api/management/commands/load_events.py
> -                    dates, created = EventDate.objects.get_or_create(dateStart=event_start_date, dateEnd=event_end_date)
On ne crée plus les EventDate, mais je ne vois par contre pas l'ajoute de date directement dans l'event (je l'ai peut-être pas vue)

2021-11-30 14:51 UTC, Aziguy commented on ifbcat_api/admin.py
>          start, end = (
J'ai réécris la fonction comme demandé à savoir:
```
    def date_range(self, obj):
        start, end = obj.start_date, obj.end_date
        if start is None:
            return None
        if end is None:
            return dateformat.format(start, "Y-m-d")
        return f'{dateformat.format(start, "Y-m-d")} - {dateformat.format(end, "Y-m-d")}'
```

2021-11-30 14:53 UTC, Aziguy commented on ifbcat_api/views.py
> +            dateStartMin=Min('start_date'),
Corrigé ? : 

```
models.Event.objects.annotate(
            dateStartMin='start_date',
            dateEndMin='end_date',
        )
```

2021-11-30 15:04 UTC, Aziguy commented on ifbcat_api/templatetags/ifbcat.py
> +                    Q(start_date=timezone.now()) | Q(end_date__isnull=False) & Q(end_date=timezone.now())
```
  model['instances'] = models.Event.objects.filter(
      Q(start_date__gte=timezone.now()) | Q(end_date__isnull=False) & Q(end_date__gte=timezone.now())
  ).order_by('-start_date')
```

2021-11-30 15:06 UTC, Aziguy commented on ifbcat_api/model/training.py
> +            d, created = Event.objects.get_or_create(start_date=start_date, end_date=end_date)
Corrigé ? :

```
        if start_date:
            event_attrs['start_date'] = start_date
            event_attrs['end_date'] = end_date

        event = Event.objects.create(**event_attrs)
```

2021-11-30 20:50 UTC, Aziguy commented on ifbcat_api/management/commands/load_events.py
> -                    dates, created = EventDate.objects.get_or_create(dateStart=event_start_date, dateEnd=event_end_date)
Je l'ai rajouté:
```
                try:
                    event, created = Event.objects.get_or_create(
                        name=event_name,
                        defaults=dict(
                            logo_url=event_logo,
                            type=event_type,
                            description=event_description,
                            # city is only a subset of event_location for the moment
                            city=event_location,
                            homepage=event_link,
                        ),
                    )
                    event.start_date = event_start_date
                    event.end_date = event_end_date
```

2021-12-01 10:01 UTC, bryan-brancotte commented on ifbcat_api/model/training.py
> +            d, created = Event.objects.get_or_create(start_date=start_date, end_date=end_date)
pas entièrement, cf review

2021-12-01 10:02 UTC, bryan-brancotte commented on ifbcat_api/templatetags/ifbcat.py
> +                    Q(start_date=timezone.now()) | Q(end_date__isnull=False) & Q(end_date=timezone.now())
:+1:

2021-12-01 10:07 UTC, bryan-brancotte commented on ifbcat_api/management/commands/load_events.py
> -                    dates, created = EventDate.objects.get_or_create(dateStart=event_start_date, dateEnd=event_end_date)
Comme cela, ça marche, mais uniquement par ce qu'il y a un save plus loins dans le code. Il faudrait mieux mettre les  `event_start_date` et `event_end_date` doivent être dans le defaults juste avant afin de grouper en un seul endroits toutes les valeurs qu'on doit définir dans le nouvelle event à créer.

2021-12-01 10:10 UTC, bryan-brancotte commented on ifbcat_api/views.py
> +            dateStartMin=Min('start_date'),
En effet on ne peut l'écrire comme cela. Il faut retirer ce bloque, et remplacé l'utilisation de dateStartMin par start_date, ainsi que dateEndMin par end_date

2021-12-01 10:40 UTC, Aziguy commented on ifbcat_api/views.py
> +            dateStartMin=Min('start_date'),
Corrigé:
```
        models.Event.objects.annotate(
            realisation_status=Case(
                When(Q(start_date__gt=timezone.now()), then=Value('future')),
                When(
                    Q(start_date__lt=timezone.now())
                    & (Q(end_date__isnull=True) | Q(end_date__lt=timezone.now())),
                    then=Value('past'),
                ),
                default=Value('ongoing'),
                output_field=CharField(),
            )
        )
```

2021-12-01 12:13 UTC, Aziguy commented on ifbcat_api/management/commands/load_events.py
> -                    dates, created = EventDate.objects.get_or_create(dateStart=event_start_date, dateEnd=event_end_date)
New script: 

```
event, created = Event.objects.get_or_create(
                        name=event_name,
                        defaults=dict(
                            logo_url=event_logo,
                            type=event_type,
                            description=event_description,
                            # city is only a subset of event_location for the moment
                            city=event_location,
                            homepage=event_link,
                            start_date=event_start_date,
                            end_date=event_end_date
                        ),
                    )
```

2021-12-01 14:24 UTC, Aziguy commented on ifbcat_api/model/event.py
> +    end_date = models.DateField(
J'ai ajouté une vérification dans la fonction ``clean()`` comme suit: 

```
    def clean(self):
        super().clean()
        errors = {}
        if self.type == Event.EventType.TRAINING_COURSE and self.training is None:
            errors.setdefault('training', []).append("training must be provided when creating a Training session")
        if self.end_date and self.start_date is None:
            errors.setdefault('start_date', []).append("start date must also be provided")
        if len(errors) > 0:
            raise ValidationError(errors)
```

2021-12-02 09:38 UTC, bryan-brancotte commented on ifbcat_api/business_logic.py
> +        models.EventDate,
EventDate doit partir non ?

2021-12-02 09:38 UTC, bryan-brancotte commented on ifbcat_api/management/commands/load_events.py
> +                            start_date=event_start_date,
:+1:

2021-12-02 09:40 UTC, bryan-brancotte commented on ifbcat_api/migrations/0165_auto_20211130_1640.py
> +        migrations.AlterField(
Il faudrait retirer cette partie sur userprofile car elle sera résolut dans une autre PR en rapport avec #173

2021-12-02 09:41 UTC, Aziguy commented on ifbcat_api/business_logic.py
> +        models.EventDate,
oui je vais complétement le supprimer de l'application après ta review du commit que je viens de faire

2021-12-02 09:42 UTC, bryan-brancotte commented on ifbcat_api/model/event.py
> +    end_date = models.DateField(
Hélas non, les validateurs ne marche pas pour valider les valeurs entre plusieurs fields : lorsque l'on voulais s'assurer que les email était en lower case un validator était la bonne architecture, mais ici on veut valider end_date en fonction de start_date, on doit donc mettre cela dans clean

2021-12-02 09:45 UTC, bryan-brancotte commented on ifbcat_api/model/training.py
> +            event_attrs['start_date'] = start_date
Ce bloque doit être avant 135 : le bloque for à partir de 135 va lire le contenu de event_attrs pour créer l'event. Tel que c'est écrit là, event_attrs est changé après la création de l'event, et les dates ne sont donc pas prises en comptes

2021-12-02 09:46 UTC, bryan-brancotte commented on ifbcat_api/serializers.py
> +
tu peux retirer cette ligne vide

2021-12-03 12:46 UTC, bryan-brancotte approved these changes
Hello @Aziguy, bon boulot !

2021-12-03 12:46 UTC, merged